### ISSUE TITLE
messed up 0.3.15 builds (should depend explicitly on abseil==*2022*)

### ISSUE THREAD

**Issue by ngam** [conda-forge/jaxlib-feedstock#132]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
... python3.10/site-packages/jaxlib/xla_extension.so: undefined symbol: _ZN4absl12lts_202206235MutexD1Ev
```

looks like we broke the build again with abseil stuff...

### Installed packages

```shell
n/a
0.3.15 cuda
```

### Environment info

```shell
n/a
0.3.15 cuda
```

**Comment by h-vetinari** [comment]
> Nothing is inherently broken per se, but our pinning is really maddening and I cannot keep track anymore.

You asked for grpc 1.46 with abseil 2021. Now you want 2022 after all?

The pinning is not so hard. Packages create a >= runtime dep for certain host deps, and some of those can only exist once in an environment, so all their dependencies need to have been built for that version.

More practically, if jaxlib was built successfully with grpc 1.46.3 and abseil 2021 before, then that is eminently still possible.

**Comment by h-vetinari** [comment]
Yeah, I get that it's annoying, thanks for sticking with it. The underlying issue is not the complexity of the pinning, but untracked ABI exposure. If we knew didn't have gaps in the knowledge/metadata which ABIs a package is affected by, then the pinning+migrators would take care of it for us!

In this case, it might be a remnant from building against the "bad" grpc builds that didn't have the run-dep on abseil, which is an extra wriggle purely due to transition issues.

Obvious solutions aside from figuring out the ABI surface affecting Jax: build only with libs that worked before (and enforce appropriately), or move everything to the newest abseil homogeneously
